### ISSUE TITLE
Code used to obtain the training data and for abstract classification

### ISSUE THREAD

**Issue by Riksi** [materialsintelligence/mat2vec#14]
Could you please share the code you used to query the APIs and filter the abstracts and for classifying them for relevance, as described in the Methods sections of the paper? Thanks.

**Comment by vtshitoyan** [comment]
Hi @Riksi, the code for download is available at https://www.github.com/materialsintelligence/matscholar, you have to configure a mongo dB. As for the classification model I am going to defer this to @LeighWeston86 since he trained the model.

**Comment by Riksi** [comment]
Thank you!
