### ISSUE TITLE
Question about the outputs

### ISSUE THREAD

**Issue by Wushengyao** [materialsintelligence/mat2vec#16]
I have successfully installed the mat2vec in the conda environment (python=3.6) and tried to reproduce your work. However, when I followed the directions under **Processing** and **Pretrained Embeddings**, no output appeared (and no error message).

For example, I run **test.txt** in the root folder of this repository, after serveral seconds running, no outputs (like pic1.jpg).

[test.txt](https://github.com/materialsintelligence/mat2vec/files/3863324/test.txt)
![pic1](https://user-images.githubusercontent.com/57943174/69141070-dfbe8f00-0afe-11ea-94d6-ea5ff1768cfc.jpg)

I am an freshman in machine learning, hoping to get your guidance. Thank you!

**Comment by jdagdelen** [comment]
Hi! Could you please include what is in test.txt? Without knowing what is in there we cannot offer guidance. Also, as a side note, you might want to change the file's extension to ".py" (e.g. "test.py") to be consistent with the naming conventions for python files.

**Comment by Wushengyao** [comment]
**In test.txt:**

from gensim.models import Word2Vec
w2v_model = Word2Vec.load("mat2vec/training/models/pretrained_embeddings")
w2v_model.wv.most_similar("thermoelectric")

And I have tried the **.py** extension, the result was the same.

**Comment by jdagdelen** [comment]
Try adding a print statement around the last line or running those lines in an interactive python shell. Although it will print the result in interactive mode, python won't write anything to the terminal when it evaluates a statement like `w2v_model.wv.most_similar("thermoelectric")` in a script.

**Comment by Wushengyao** [comment]
I get it. Thank you very much！

**Comment by jdagdelen** [comment]
You're welcome. :)
