### ISSUE TITLE
Training my own word embeddings

### ISSUE THREAD

**Issue by TasnimGh** [materialsintelligence/mat2vec#18]
Hi,
I am trying to train my own word embeddings on my own corpus using your model. Could you please help me step by step how can I do that?
I run the model  according to your instructions in the readme file and it works.

**Comment by vt257** [comment]
Hi, does the [Training](https://github.com/materialsintelligence/mat2vec#training) section of the README file answer your question? You have to change the path in the `--corpus` flag to your own pre-processed corpus, and that should be enough. You can also run `python phrase2vec.py --help` for more info.

**Comment by vtshitoyan** [comment]
Hi, does the [Training](https://github.com/materialsintelligence/mat2vec#training) section of the README file answer your question? You have to change the path in the `--corpus` flag to your own pre-processed corpus, and that should be enough. You can also run python `phrase2vec.py` --help for more info.

**Comment by TasnimGh** [comment]
Thank you, I did it and it helped. For the pre-processed corpus. Can I uses the process.py? How?

**Comment by vtshitoyan** [comment]
https://github.com/materialsintelligence/mat2vec#processing
