### ISSUE TITLE
I was able to train and use this on the COVID papers dataset

### ISSUE THREAD

**Issue by Tylersuard** [materialsintelligence/mat2vec#20]
I just wanted to say thank you :)

**Comment by leotam** [comment]
Do you have a link to your results?

**Comment by jdagdelen** [comment]
@Tylersuard I would love to hear more about what you're building with the embeddings you created.

**Comment by Tylersuard** [comment]
Indeed!  https://www.kaggle.com/tylersuard/mat2vec-covid-papers-unexpected-word-asociations?scriptVersionId=30790274

I was just entering this for a Kaggle competition.  They dumped a big pile of pdf documents on us and asked us to extract information from them.  I thought I would give Mat2Vec a try, since it's interested me for the last 6 months.
