### ISSUE TITLE
Drug repurposing for COVID

### ISSUE THREAD

**Issue by Tylersuard** [materialsintelligence/mat2vec#21]
Hello @jdagdelen .  You mentioned in an earlier thread that Mat2Vec could be used for drug repurposing.  Experiments are currently underway to perform simulations on 8,000 drugs approved by the FDA, and 77 of those compounds have been selected as being likely candidates for COVID treatment.  https://onezero.medium.com/the-worlds-most-powerful-supercomputer-has-entered-the-fight-against-coronavirus-3e98c4d67459

If we use Mat2vec for the same drug repurposing task, the intersection of our work and theirs might yield a shortened list of candidate compounds.  What do you think about getting started on this?  I can use the program but I don’t have a deep enough understanding of it to figure out how to discover new knowledge from it.  Would you like to collaborate?

**Comment by jdagdelen** [comment]
Hi Tyler, In the interim we have started a team to work on both this task and other COVID literature analysis. We're working on applying this method to a special corpus of COVID-related literature in collaboration with researchers at the Innovative Genomics Institute here in Berkeley. Please let me know if you make any progress and I'll let you know about developments on our end as they happen.

**Comment by jdagdelen** [comment]
I would love to collaborate more closely, but we can't share our data with outside collaborators due to copyright reasons so it limits what we can do.

**Comment by Tylersuard** [comment]
I understand completely.  Thank you, and I hope we get to work together in the future.
