### ISSUE TITLE
Script to fetch cleaned abstracts

### ISSUE THREAD

**Issue by leotam** [materialsintelligence/mat2vec#22]
I noticed you've nicely provided the DOIs, but a simple pull will fetch the article in raw html. Might you have a recommendation on grabbing the cleaned abstracts as you did it?  There's the several dataset splits that you mentioned being quite influential on the final result.

**Comment by jdagdelen** [comment]
Hi, 

Sorry this issue went unanswered for so long. One can use the Scopus API and the dois to scrape most of the content. Unfortunately we can't share dumps of our corpus and metadata due to copyright.
