### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'common_terms'

### ISSUE THREAD

**Issue by TasnimGh** [materialsintelligence/mat2vec#25]
Hi,
I tried to train a model and I got this error:

Traceback (most recent call last):
  File "C:\Users\T\desktop\backup\mat2vec-master\mat2vec\training\phrase2vec.py", line 164, in <module>
    sentences, phraser = wordgrams(processed_sentences,
  File "C:\Users\T\desktop\backup\mat2vec-master\mat2vec\training\phrase2vec.py", line 43, in wordgrams
    phrases = Phrases(
TypeError: __init__() got an unexpected keyword argument 'common_terms'

**Comment by booleank** [comment]
I have the same issue. Did you end up fixing it?

**Comment by TasnimGh** [comment]
Yes, you need to have gensim version= 3.7 or 3.8.

**Comment by booleank** [comment]
How did you go about changing the version. Mine is on 4.0.1.

**Comment by TasnimGh** [comment]
conda install gensim==3.8

**Comment by hasan-sayeed** [comment]
I tried gensim 3.7.3 and 3.8 but still having this problem.

@TasnimGh did you solve this?
![err](https://user-images.githubusercontent.com/47003757/128135163-4e93a855-3a2c-41c1-8c18-e1386b673a34.PNG)

**Comment by TasnimGh** [comment]
I think you need to use python 3.6.


Sent from Yahoo Mail for iPhone


On Wednesday, August 4, 2021, 2:52 AM, Hasan Muhammad Sayeed ***@***.***> wrote:




I tried gensim 3.7.3 and 3.8 but still having this problem.

@TasnimGh could you solve this?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hasan-sayeed** [comment]
Tried downgrading python to 3.6.13 and still having this problem. Also tried to install the whole thing again using python 3.6 but then got an error- `ERROR: No matching distribution found for numpy>=1.20.1`. Numpy 1.20.1 seems to have dropped support for python 3.6. It requires =>3.7 now. Can anyone suggest what should I do? Thanks.

**Comment by jdagdelen** [comment]
Try using python 3.8. I think the issue with DAWG that caused us to require python 3.6 has been resolved.

**Comment by hasan-sayeed** [comment]
Just tried. The same thing happened.

Edit: Forgot to install gensim 3.8. Tried it, and the problem is solved! Thank you guys!

**Comment by JJery-web** [comment]
> Yes, you need to have gensim version= 3.7 or 3.8.

pip install gensim==3.7  helps me
