### ISSUE TITLE
Setup requirements error

### ISSUE THREAD

**Issue by dbcraig** [materialsintelligence/mat2vec#6]
Had an issue (from within a fresh conda environment) running:

`pip install -r requirements.txt`

After successfully compiling packages installation ultimately failed with:
```
...
Installing collected packages: monty, regex, urllib3, requests, unidecode, ruamel.yaml, pydispatcher, tabulate, spglib, palettable, pymatgen, pycryptodome, pdfminer.six, python-crfsuite, cssselect, appdirs, DAWG, chemdataextractor, jmespath, botocore, s3transfer, boto3, smart-open, gensim, tqdm
  Found existing installation: urllib3 1.12
ERROR: Cannot remove entries from nonexistent file /xxx/.conda/envs/tshitoyan/lib/python3.6/site-packages/easy-install.pth
```

The solution was to re-run pip with the --ignore-installed option:

`pip install --ignore-installed -r requirements.txt`

Beyond that, everything installed and ran as expected.
Hope this saves some headaches for others.

Great work!

Doug

**Comment by YuanJ-i** [comment]
same issue as yours

**Comment by YuanJ-i** [comment]
solved by downgrade to python 3.6

**Comment by YuanJ-i** [comment]
> 
> 
> solved by downgrade to python 3.6

plus, you need a vpn if you are in china, otherwise it will be very slow downloading process

**Comment by jdagdelen** [comment]
I've added checking for Python 3.6 in #8. @vtshitoyan could you please review and merge?

**Comment by vtshitoyan** [comment]
@jdagdelen I am not sure this fixes the issue since it happens during the `pip install -r requirements.txt`?

**Comment by jdagdelen** [comment]
I'm adding the `--ignore-installed` flag to the recommended setup steps so new users should hopefully avoid running into this. I'm closing this now since discussion seems to have resolved but feel free to reopen if you want to continue discussing this issue.
