### ISSUE TITLE
Other applications

### ISSUE THREAD

**Issue by Tylersuard** [materialsintelligence/mat2vec#9]
How can this software be applied to other research areas? Space travel/propulsion, physics, history, etc?  Thank you!

**Comment by jdagdelen** [comment]
It would be relatively straightforward to train embeddings for another discipline (given that you have a corpus of text for that discipline.) We expect that similar utility can be achieved (for example with drug repurposing).

**Comment by Tylersuard** [comment]
Thank you for your response.  I gave a speech on AI at a conference this weekend, and talked about Mat2Vec in it.  After my speech was over, I got many questions about Mat2Vec and how it works.  It was a big hit :)

**Comment by vtshitoyan** [comment]
Thanks @Tylersuard! Happy to hear that.
